const GET_NEWS_FEED_PENDING = 'GET_NEWS_FEED_PENDING';
const GET_NEWS_FEED_FULFILLED = 'GET_NEWS_FEED_FULFILLED';
const GET_NEWS_FEED_REJECTED = 'GET_NEWS_FEED_REJECTED';
const ADD_NEW_FEED_PENDING = 'ADD_NEW_FEED_PENDING';
const ADD_NEW_FEED_FULFILLED = 'ADD_NEW_FEED_FULFILLED';
const ADD_NEW_FEED_REJECTED = 'ADD_NEW_FEED_REJECTED';

export {
  GET_NEWS_FEED_PENDING,
  GET_NEWS_FEED_FULFILLED,
  GET_NEWS_FEED_REJECTED,
  ADD_NEW_FEED_PENDING,
  ADD_NEW_FEED_FULFILLED,
  ADD_NEW_FEED_REJECTED,
};
