const GET_NEWS_FEED_PENDING = 'GET_NEWS_FEED_PENDING';
const GET_NEWS_FEED_FULFILLED = 'GET_NEWS_FEED_FULFILLED';
const GET_NEWS_FEED_REJECTED = 'GET_NEWS_FEED_REJECTED';

export { GET_NEWS_FEED_PENDING, GET_NEWS_FEED_FULFILLED, GET_NEWS_FEED_REJECTED };
